FROM debian:stretch
RUN echo "deb-src http://deb.debian.org/debian stretch main" >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get -y build-dep iptables \
    && apt-get -y install libpcap-dev libnfnetlink-dev
WORKDIR /tmp/iptables
COPY iptables .
RUN ./autogen.sh && ./configure LDFLAGS=--static --enable-bpf-compiler --disable-nftables --enable-ipv6 && make -C utils nfbpf_compile

